### ISSUE TITLE
UIactionsheet Depricated

### ISSUE THREAD

**Issue by kunalgupta1593** [ryanmaxwell/UIActionSheet-Blocks#10]
This gives warning
 UIActionSheet is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleActionSheet instead
Please update the library

**Comment by ryanmaxwell** [comment]
Hi - Please check out [UIAlertController-Blocks](https://github.com/ryanmaxwell/UIAlertController-Blocks)
