### ISSUE TITLE
Lots of syntax errors with this new build

### ISSUE THREAD

**Issue by MarkMolina** [ryanmaxwell/UIActionSheet-Blocks#8]
![screen shot 2015-04-09 at 10 27 06](https://cloud.githubusercontent.com/assets/3329668/7062998/ff493a9c-dea2-11e4-9d5d-9fb0647cca7a.png)

**Comment by ryanmaxwell** [comment]
Hi - I published this new build today with the release of Xcode 6.3 final. Update your xcode install and try again.

**Comment by MarkMolina** [comment]
Ah sorry. Didn't know about any new version of Xcode. Let me try that.

**Comment by Omar-M** [comment]
I had the same issue, may be it will be useful for others developer to say it in the homepage.

**Comment by ryanmaxwell** [comment]
I've added a note to the readme about this now.
