### ISSUE TITLE
Version 0.9 very strange header file implementation.

### ISSUE THREAD

**Issue by mixdesign** [ryanmaxwell/UIActionSheet-Blocks#9]
Can you confirm that version 0.9 is working in your projects? There are very strange codes. =)

**Comment by ryanmaxwell** [comment]
Check the update to the readme - v 0.9 will need Xcode 6.3 which has now been released. If you're using an older Xcode - pin your podspec to an older version. Thanks

**Comment by mixdesign** [comment]
I see. 
Hope to get update for AppCode. Because Appcode 3.1 doesn't support new Objective-C nullability annotations.
